# Generated by Django 4.2.7 on 2024-04-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('manufacturer', models.CharField(max_length=200)),
                ('active_ingredients', models.CharField(max_length=200)),
                ('alcohol_warning', models.TextField()),
                ('pregnancy_warning', models.TextField()),
                ('breastfeeding_warning', models.TextField()),
                ('image_url', models.URLField()),
            ],
        ),
    ]
