# Generated by Django 4.2.7 on 2024-04-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_medicine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='image_url',
        ),
        migrations.AddField(
            model_name='medicine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
