# Generated by Django 4.2.7 on 2024-04-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='digital',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
